language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: XDEBUG_OFF="yes"
    - php: 7.0
      env: XDEBUG_OFF="yes"

script:
  - sh -c 'if [ "$XDEBUG_OFF" = "yes" ]; then
         phpenv config-rm xdebug.ini
     fi;'

  - composer update-all
  - composer test

after_script:
  - composer coveralls
